// <auto-generated />
using System;
using FoodTraceability.Modules.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTraceability.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260902194455_AddUnit")]
    partial class AddUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTraceability.Modules.Catalog.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("article_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_article_article_id_organization_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_article_product_id");

                    b.HasIndex("OrganizationId", "Gtin")
                        .IsUnique()
                        .HasDatabaseName("ix_article_organization_id_gtin");

                    b.ToTable("article", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_article_gtin_format", "gtin IS NULL OR (gtin ~ '^[0-9]+$' AND length(gtin) IN (8, 12, 13, 14))");
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", "catalog");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Catalog.Domain.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dimension");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_code");

                    b.ToTable("unit", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_unit_dimension", "dimension IN ('MASS', 'VOLUME', 'COUNT')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ba563a7-f314-57d8-b3d7-ee5c12ff1085"),
                            Code = "KG",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimension = "MASS",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = new Guid("5e726b86-c672-5ed0-9601-904328038341"),
                            Code = "G",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimension = "MASS",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = new Guid("8d8ed466-8384-5e44-8430-eee76f15a180"),
                            Code = "L",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimension = "VOLUME",
                            Symbol = "l"
                        },
                        new
                        {
                            Id = new Guid("dd541026-8821-53a3-97de-f0a974327970"),
                            Code = "ML",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimension = "VOLUME",
                            Symbol = "ml"
                        },
                        new
                        {
                            Id = new Guid("d227d884-ef6c-5667-9587-1d9fdee6836e"),
                            Code = "PCS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dimension = "COUNT",
                            Symbol = "pcs"
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Catalog.Domain.Article", b =>
                {
                    b.HasOne("FoodTraceability.Modules.Catalog.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_product_product_id");
                });
#pragma warning restore 612, 618
        }
    }
}
