<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\FoodTraceability.Platform.Contracts\FoodTraceability.Platform.Contracts.csproj" />
    <ProjectReference Include="..\FoodTraceability.Modules.Quality.Domain\FoodTraceability.Modules.Quality.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FoodTraceability.BuildingBlocks\FoodTraceability.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
