<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FoodTraceability.Modules.Identity.Application\FoodTraceability.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\FoodTraceability.Modules.Identity.Domain\FoodTraceability.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FoodTraceability.BuildingBlocks\FoodTraceability.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
