// <auto-generated />
using System;
using FoodTraceability.Modules.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTraceability.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260901115402_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            Code = "PLATFORM_ADMIN",
                            Name = "PlatformAdmin"
                        },
                        new
                        {
                            Id = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            Code = "ORGANIZATION_ADMIN",
                            Name = "OrganizationAdmin"
                        },
                        new
                        {
                            Id = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            Code = "PRODUCER",
                            Name = "Producer"
                        },
                        new
                        {
                            Id = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            Code = "PROCESSOR",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            Code = "QUALITY_MANAGER",
                            Name = "QualityManager"
                        },
                        new
                        {
                            Id = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            Code = "LABORATORY",
                            Name = "Laboratory"
                        },
                        new
                        {
                            Id = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            Code = "BOTTLER",
                            Name = "Bottler"
                        },
                        new
                        {
                            Id = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            Code = "LOGISTICS",
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            Code = "RETAILER",
                            Name = "Retailer"
                        },
                        new
                        {
                            Id = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            Code = "AUDITOR",
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", "identity");
                });
#pragma warning restore 612, 618
        }
    }
}
