// <auto-generated />
using System;
using FoodTraceability.Modules.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTraceability.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260901141210_AddRolePermissions")]
    partial class AddRolePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_code");

                    b.ToTable("permission", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5239d89e-16e3-586b-9996-32085b6b867d"),
                            Code = "organization.read"
                        },
                        new
                        {
                            Id = new Guid("b9c07ec4-7da3-570b-b279-57f758496798"),
                            Code = "organization.manage"
                        },
                        new
                        {
                            Id = new Guid("542cd3e3-27c8-5a3d-b634-10cff370a922"),
                            Code = "user.read"
                        },
                        new
                        {
                            Id = new Guid("227a9dd3-048c-51e8-aae9-c0268a185640"),
                            Code = "user.manage"
                        },
                        new
                        {
                            Id = new Guid("51d975f4-e516-525c-a24b-b94fd8cfdea1"),
                            Code = "role.read"
                        },
                        new
                        {
                            Id = new Guid("5362b9ec-0f34-51f9-9423-ec9940ec8e22"),
                            Code = "permission.read"
                        },
                        new
                        {
                            Id = new Guid("13fae5e7-0a2d-5b72-9401-3c9e398b2b55"),
                            Code = "product.read"
                        },
                        new
                        {
                            Id = new Guid("becb86f7-1a71-5ccb-b0ab-3aade89e6177"),
                            Code = "product.create"
                        },
                        new
                        {
                            Id = new Guid("06de594f-5714-5198-b877-5b84fdb8a1bc"),
                            Code = "product.update"
                        },
                        new
                        {
                            Id = new Guid("8d153853-ab36-5e34-8537-2e05556feeee"),
                            Code = "lot.read"
                        },
                        new
                        {
                            Id = new Guid("da54dd5a-9013-5c1b-8b4e-fdc30258e02f"),
                            Code = "lot.create"
                        },
                        new
                        {
                            Id = new Guid("a131fb8f-4ffb-510e-8aa3-2d7fa78c3383"),
                            Code = "lot.update"
                        },
                        new
                        {
                            Id = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf"),
                            Code = "trace.read"
                        },
                        new
                        {
                            Id = new Guid("f999fb2f-ee88-5dd9-a4ec-9170587f7d9b"),
                            Code = "trace.event.create"
                        },
                        new
                        {
                            Id = new Guid("d8f29f61-9bbb-5659-8b88-559242e75918"),
                            Code = "quality.read"
                        },
                        new
                        {
                            Id = new Guid("123005cc-2642-5a72-b2d8-f3f5d989bd32"),
                            Code = "quality.sample.create"
                        },
                        new
                        {
                            Id = new Guid("bad85ec4-523c-5505-b4aa-933cd062add9"),
                            Code = "quality.result.create"
                        },
                        new
                        {
                            Id = new Guid("87bbc734-d0ce-544b-ad62-ddefb7f56a80"),
                            Code = "quality.release"
                        },
                        new
                        {
                            Id = new Guid("e577d2b4-c89d-58db-a0f7-5be7f040734a"),
                            Code = "quality.block"
                        },
                        new
                        {
                            Id = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d"),
                            Code = "document.read"
                        },
                        new
                        {
                            Id = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b"),
                            Code = "document.upload"
                        },
                        new
                        {
                            Id = new Guid("e6708b10-357c-5285-a292-69deae973983"),
                            Code = "transport.read"
                        },
                        new
                        {
                            Id = new Guid("b0f144ee-b4da-5e04-9d5f-253a24922db2"),
                            Code = "transport.create"
                        },
                        new
                        {
                            Id = new Guid("27c75590-f8fe-5fbe-afc4-190fcca52776"),
                            Code = "delivery.read"
                        },
                        new
                        {
                            Id = new Guid("d8f57584-4487-5fa8-8a59-5e7effd62f06"),
                            Code = "delivery.create"
                        },
                        new
                        {
                            Id = new Guid("573fe7e9-c8f3-5b46-a885-3f2ae13ca228"),
                            Code = "audit.read"
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            Code = "PLATFORM_ADMIN",
                            Name = "PlatformAdmin"
                        },
                        new
                        {
                            Id = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            Code = "ORGANIZATION_ADMIN",
                            Name = "OrganizationAdmin"
                        },
                        new
                        {
                            Id = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            Code = "PRODUCER",
                            Name = "Producer"
                        },
                        new
                        {
                            Id = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            Code = "PROCESSOR",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            Code = "QUALITY_MANAGER",
                            Name = "QualityManager"
                        },
                        new
                        {
                            Id = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            Code = "LABORATORY",
                            Name = "Laboratory"
                        },
                        new
                        {
                            Id = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            Code = "BOTTLER",
                            Name = "Bottler"
                        },
                        new
                        {
                            Id = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            Code = "LOGISTICS",
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            Code = "RETAILER",
                            Name = "Retailer"
                        },
                        new
                        {
                            Id = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            Code = "AUDITOR",
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.ToTable("role_permission", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("5239d89e-16e3-586b-9996-32085b6b867d")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("b9c07ec4-7da3-570b-b279-57f758496798")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("542cd3e3-27c8-5a3d-b634-10cff370a922")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("227a9dd3-048c-51e8-aae9-c0268a185640")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("51d975f4-e516-525c-a24b-b94fd8cfdea1")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("5362b9ec-0f34-51f9-9423-ec9940ec8e22")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("13fae5e7-0a2d-5b72-9401-3c9e398b2b55")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("becb86f7-1a71-5ccb-b0ab-3aade89e6177")
                        },
                        new
                        {
                            RoleId = new Guid("ec72b8b5-2610-5efd-aa7f-6aa59889da7d"),
                            PermissionId = new Guid("06de594f-5714-5198-b877-5b84fdb8a1bc")
                        },
                        new
                        {
                            RoleId = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            PermissionId = new Guid("5239d89e-16e3-586b-9996-32085b6b867d")
                        },
                        new
                        {
                            RoleId = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            PermissionId = new Guid("b9c07ec4-7da3-570b-b279-57f758496798")
                        },
                        new
                        {
                            RoleId = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            PermissionId = new Guid("542cd3e3-27c8-5a3d-b634-10cff370a922")
                        },
                        new
                        {
                            RoleId = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            PermissionId = new Guid("227a9dd3-048c-51e8-aae9-c0268a185640")
                        },
                        new
                        {
                            RoleId = new Guid("00ec29aa-1bc7-540e-b04d-02c3497f50b3"),
                            PermissionId = new Guid("51d975f4-e516-525c-a24b-b94fd8cfdea1")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("13fae5e7-0a2d-5b72-9401-3c9e398b2b55")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("da54dd5a-9013-5c1b-8b4e-fdc30258e02f")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("a131fb8f-4ffb-510e-8aa3-2d7fa78c3383")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("f999fb2f-ee88-5dd9-a4ec-9170587f7d9b")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("d8c0f985-5ce5-59b9-bf3b-71ae6bc5616a"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("13fae5e7-0a2d-5b72-9401-3c9e398b2b55")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("da54dd5a-9013-5c1b-8b4e-fdc30258e02f")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("a131fb8f-4ffb-510e-8aa3-2d7fa78c3383")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("f999fb2f-ee88-5dd9-a4ec-9170587f7d9b")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("351aaedc-26d7-5406-9109-f4f8139ec1a8"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("13fae5e7-0a2d-5b72-9401-3c9e398b2b55")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("da54dd5a-9013-5c1b-8b4e-fdc30258e02f")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("a131fb8f-4ffb-510e-8aa3-2d7fa78c3383")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("f999fb2f-ee88-5dd9-a4ec-9170587f7d9b")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("34644a1b-9bbb-5005-98a1-b3584dd8bf69"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("d8f29f61-9bbb-5659-8b88-559242e75918")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("123005cc-2642-5a72-b2d8-f3f5d989bd32")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("87bbc734-d0ce-544b-ad62-ddefb7f56a80")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("e577d2b4-c89d-58db-a0f7-5be7f040734a")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("38623612-6286-55ce-9af2-ea523f760be3"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            PermissionId = new Guid("d8f29f61-9bbb-5659-8b88-559242e75918")
                        },
                        new
                        {
                            RoleId = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            PermissionId = new Guid("bad85ec4-523c-5505-b4aa-933cd062add9")
                        },
                        new
                        {
                            RoleId = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("2ef0f055-298c-512e-a35e-10d180133f51"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("e6708b10-357c-5285-a292-69deae973983")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("b0f144ee-b4da-5e04-9d5f-253a24922db2")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("27c75590-f8fe-5fbe-afc4-190fcca52776")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("d8f57584-4487-5fa8-8a59-5e7effd62f06")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("222d9d3e-a711-5607-820a-59c9f497bbaf"),
                            PermissionId = new Guid("78562e51-4c55-5309-94b3-c96ef465ad9b")
                        },
                        new
                        {
                            RoleId = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            PermissionId = new Guid("27c75590-f8fe-5fbe-afc4-190fcca52776")
                        },
                        new
                        {
                            RoleId = new Guid("0002868f-4330-5c7c-aac4-77420d2aff52"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            PermissionId = new Guid("8d153853-ab36-5e34-8537-2e05556feeee")
                        },
                        new
                        {
                            RoleId = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            PermissionId = new Guid("1ed56bb0-2b7b-5c76-a63a-5072027ee5bf")
                        },
                        new
                        {
                            RoleId = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            PermissionId = new Guid("d8f29f61-9bbb-5659-8b88-559242e75918")
                        },
                        new
                        {
                            RoleId = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            PermissionId = new Guid("ad1e5f46-77ad-5029-85b1-5048d78c6f8d")
                        },
                        new
                        {
                            RoleId = new Guid("a187d055-fa04-56ef-b488-2b6ad6216007"),
                            PermissionId = new Guid("573fe7e9-c8f3-5b46-a885-3f2ae13ca228")
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("FoodTraceability.Modules.Identity.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("FoodTraceability.Modules.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");
                });
#pragma warning restore 612, 618
        }
    }
}
