// <auto-generated />
using System;
using FoodTraceability.Modules.Traceability.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTraceability.Modules.Traceability.Infrastructure.Migrations
{
    [DbContext(typeof(TraceabilityDbContext))]
    [Migration("20260912120000_AddLotOrganizationAlternateKey")]
    partial class AddLotOrganizationAlternateKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.EventInput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_input_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasColumnOrder(4);

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id")
                        .HasColumnOrder(5);

                    b.HasKey("Id")
                        .HasName("pk_event_input");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_event_input_lot_id");

                    b.HasIndex("EventId", "LotId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_input_event_id_lot_id");

                    b.HasIndex("EventId", "OrganizationId")
                        .HasDatabaseName("ix_event_input_event_id_organization_id");

                    b.HasIndex("LotId", "OrganizationId", "UnitId")
                        .HasDatabaseName("ix_event_input_lot_id_organization_id_unit_id");

                    b.ToTable("event_input", "trace", t =>
                        {
                            t.HasCheckConstraint("ck_event_input_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.EventOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_output_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id")
                        .HasColumnOrder(3);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity")
                        .HasColumnOrder(4);

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id")
                        .HasColumnOrder(5);

                    b.HasKey("Id")
                        .HasName("pk_event_output");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_event_output_lot_id");

                    b.HasIndex("EventId", "LotId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_output_event_id_lot_id");

                    b.HasIndex("EventId", "OrganizationId")
                        .HasDatabaseName("ix_event_output_event_id_organization_id");

                    b.HasIndex("LotId", "OrganizationId", "UnitId")
                        .HasDatabaseName("ix_event_output_lot_id_organization_id_unit_id");

                    b.ToTable("event_output", "trace", t =>
                        {
                            t.HasCheckConstraint("ck_event_output_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_event_type");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_event_type_code");

                    b.ToTable("event_type", "trace", t =>
                        {
                            t.HasCheckConstraint("ck_event_type_classification", "classification IN ('TRACEABILITY', 'TRACEABILITY_AWAITING_LOGISTICS', 'LOGISTICS', 'QUALITY', 'DEFERRED')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("784ded8c-54a9-595e-b2b2-10acbf16e887"),
                            Classification = "TRACEABILITY",
                            Code = "HARVEST",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0195e858-b3f0-54be-ad01-581f168ecf8f"),
                            Classification = "TRACEABILITY_AWAITING_LOGISTICS",
                            Code = "RECEIVE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4e471a84-b9d6-5618-aee9-6ca1f3373ddd"),
                            Classification = "LOGISTICS",
                            Code = "TRANSFER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("26614721-e8f4-5513-a9cf-0c2422fc003b"),
                            Classification = "DEFERRED",
                            Code = "STORE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b2830815-b10e-5507-9ed3-13679fc08e5e"),
                            Classification = "TRACEABILITY",
                            Code = "PRESS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("99147ae3-6e5b-599d-830d-3f55d80d8242"),
                            Classification = "TRACEABILITY",
                            Code = "PROCESS",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("58929c0a-8d65-5a38-a6d1-6d74cb144b44"),
                            Classification = "TRACEABILITY",
                            Code = "MIX",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5373e85b-e968-55b7-a8bc-7f44008647d2"),
                            Classification = "TRACEABILITY",
                            Code = "SPLIT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("49163869-4ef0-501f-984d-ab3adb5e1996"),
                            Classification = "TRACEABILITY",
                            Code = "SAMPLE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("dbe268c4-4290-5249-b3ad-5ffe81b3fdc8"),
                            Classification = "QUALITY",
                            Code = "QUALITY_RELEASE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7a5bb899-9c04-5dbf-9341-64bc402c2ed3"),
                            Classification = "QUALITY",
                            Code = "BLOCK",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0283c126-a16a-516d-aeec-b246af44b88a"),
                            Classification = "QUALITY",
                            Code = "UNBLOCK",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("76ad5624-efd3-54d8-903e-7a9fdb221adb"),
                            Classification = "TRACEABILITY",
                            Code = "BOTTLE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b94a7503-17b1-506a-a738-b169290da379"),
                            Classification = "DEFERRED",
                            Code = "PACK",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7b93d110-a9e4-53af-b3fc-5f7580f7a8f6"),
                            Classification = "LOGISTICS",
                            Code = "SHIP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("243a920d-b978-5202-896e-6428a74a2c22"),
                            Classification = "LOGISTICS",
                            Code = "DELIVER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3022cd5f-94b0-52d8-af19-2f1959360602"),
                            Classification = "TRACEABILITY_AWAITING_LOGISTICS",
                            Code = "SELL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ad863244-bf75-5f34-886a-eb400f82985d"),
                            Classification = "TRACEABILITY_AWAITING_LOGISTICS",
                            Code = "RETURN",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("36ca16f4-df60-56f3-8d30-60af75da9c92"),
                            Classification = "TRACEABILITY",
                            Code = "DISPOSE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_lot");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_lot_lot_id_organization_id");

                    b.HasAlternateKey("Id", "OrganizationId", "UnitId")
                        .HasName("ak_lot_lot_id_organization_id_unit_id");

                    b.ToTable("lot", "trace", t =>
                        {
                            t.HasCheckConstraint("ck_lot_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.TraceabilityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_traceability_event");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_traceability_event_event_id_organization_id");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_traceability_event_event_type_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_traceability_event_occurred_at");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_traceability_event_organization_id");

                    b.ToTable("traceability_event", "trace");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.EventInput", b =>
                {
                    b.HasOne("FoodTraceability.Modules.Traceability.Domain.TraceabilityEvent", null)
                        .WithMany("Inputs")
                        .HasForeignKey("EventId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_input_trace_traceability_event");

                    b.HasOne("FoodTraceability.Modules.Traceability.Domain.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotId", "OrganizationId", "UnitId")
                        .HasPrincipalKey("Id", "OrganizationId", "UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_input_trace_lot");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.EventOutput", b =>
                {
                    b.HasOne("FoodTraceability.Modules.Traceability.Domain.TraceabilityEvent", null)
                        .WithMany("Outputs")
                        .HasForeignKey("EventId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_output_trace_traceability_event");

                    b.HasOne("FoodTraceability.Modules.Traceability.Domain.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotId", "OrganizationId", "UnitId")
                        .HasPrincipalKey("Id", "OrganizationId", "UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_output_trace_lot");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.TraceabilityEvent", b =>
                {
                    b.HasOne("FoodTraceability.Modules.Traceability.Domain.EventType", null)
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_traceability_event_trace_event_type");
                });

            modelBuilder.Entity("FoodTraceability.Modules.Traceability.Domain.TraceabilityEvent", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}
