<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Platform\FoodTraceability.Platform.Persistence\FoodTraceability.Platform.Persistence.csproj" />
    <ProjectReference Include="..\Modules\Identity\FoodTraceability.Modules.Identity.Infrastructure\FoodTraceability.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Organizations\FoodTraceability.Modules.Organizations.Infrastructure\FoodTraceability.Modules.Organizations.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\FoodTraceability.Modules.Catalog.Infrastructure\FoodTraceability.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Traceability\FoodTraceability.Modules.Traceability.Infrastructure\FoodTraceability.Modules.Traceability.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Quality\FoodTraceability.Modules.Quality.Infrastructure\FoodTraceability.Modules.Quality.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Documents\FoodTraceability.Modules.Documents.Infrastructure\FoodTraceability.Modules.Documents.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Logistics\FoodTraceability.Modules.Logistics.Infrastructure\FoodTraceability.Modules.Logistics.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\PublicTrace\FoodTraceability.Modules.PublicTrace.Infrastructure\FoodTraceability.Modules.PublicTrace.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Audit\FoodTraceability.Modules.Audit.Infrastructure\FoodTraceability.Modules.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Industries\OliveOil\FoodTraceability.Modules.Industries.OliveOil.Infrastructure\FoodTraceability.Modules.Industries.OliveOil.Infrastructure.csproj" />
  </ItemGroup>
</Project>
